import { ArrowDown, ArrowRight, BadgeDollarSign, Building2, CalendarDays, FileCheck2, KeyRound, MapPin, Scale, ShieldCheck, Sprout, Wheat } from "lucide-react";
import { whatsappUrl } from "../../../config/template.config";
import headquarters from "../../../assets/local_mendonca.jpg";
import teamPhoto from "../../../assets/equipe-essencial.jpg";

const ruralUrl = whatsappUrl("Olá! Vim pelo site e gostaria de uma análise do meu caso de Previdenciário Rural.");
const propertyUrl = whatsappUrl("Quero analisar meu contrato de imóvel na planta.");

export function HomePage() {
  return <>
    <section className="hero" id="inicio"><div className="hero-media"/><div className="hero-content container"><span className="eyebrow">Previdenciário Rural</span><h1>Seu trabalho no campo tem história. <span>Seus direitos também.</span></h1><p>O <b>Mendonça Advogados</b>, liderado pelo Dr. Allyson Mendonça, analisa cada caso de forma individual para orientar trabalhadores rurais e suas famílias.</p><a className="button rural-button" href={ruralUrl} target="_blank" rel="noreferrer">Quero analisar meu caso <ArrowRight/></a></div><a className="scroll-hint" href="#areas" aria-label="Ver áreas de atuação"><ArrowDown/></a></section>

    <section className="dark-section section-pad" id="areas"><div className="container"><div className="section-heading centered"><span className="eyebrow">Como podemos ajudar</span><h2>Atendimento direcionado desde o primeiro contato</h2><p>Escolha o núcleo relacionado ao seu caso e avance para uma triagem especializada.</p></div><div className="area-grid">
      <article className="area-card area-card-featured"><div className="card-photo rural-photo"><span>Foco inicial</span></div><div className="area-copy"><Wheat/><h3>Aposentadoria Rural &amp; Benefício Assistencial (BPC/LOAS)</h3><p>Trabalhou na roça, lavoura, pesca artesanal ou em regime de economia familiar? Entenda os requisitos e os documentos que podem ajudar a comprovar sua atividade.</p><a className="button rural-button" href={ruralUrl} target="_blank" rel="noreferrer">Consultar meu caso <ArrowRight/></a></div></article>
      <article className="area-card"><div className="card-photo property-photo"><span>Imobiliário bancário</span></div><div className="area-copy"><KeyRound/><h3>Problemas com Imóvel na Planta</h3><p>Sua obra financiada pela Caixa está atrasada? Saiba como questionar juros de obra e buscar as indenizações aplicáveis.</p><a className="button property-button" href={propertyUrl} target="_blank" rel="noreferrer">Analisar meu contrato <ArrowRight/></a></div></article>
    </div></div></section>

    <section className="ivory-section section-pad rural-section" id="rural"><div className="container rural-layout"><div className="rural-intro"><span className="eyebrow">Aposentadoria rural</span><h2>Aposentadoria por idade para quem trabalhou na terra</h2><p>Veja os pontos principais de forma simples. Nossa equipe analisa cada situação individualmente.</p><div className="framed-photo rural-detail" role="img" aria-label="Trabalho rural no campo"/></div><div className="rural-topics">
      <article><div className="topic-icon"><CalendarDays/></div><div><span>01</span><h3>Idade mínima</h3><p>Mulheres a partir de 55 anos e homens a partir de 60 anos.</p></div></article>
      <article><div className="topic-icon"><Sprout/></div><div><span>02</span><h3>Atividade rural</h3><p>Trabalho na lavoura, roça ou pesca, inclusive em agricultura familiar.</p></div></article>
      <article><div className="topic-icon"><BadgeDollarSign/></div><div><span>03</span><h3>Sem carnê do INSS</h3><p>O benefício pode ser possível mesmo sem contribuições mensais ao INSS.</p></div></article>
      <article><div className="topic-icon"><FileCheck2/></div><div><span>04</span><h3>Como comprovar</h3><p>Certidões, fichas de sindicato, documentos escolares e registros da terra podem ajudar.</p></div></article>
      <a className="button rural-button" href={ruralUrl} target="_blank" rel="noreferrer">Falar com especialista previdenciário <ArrowRight/></a>
    </div></div></section>

    <section className="dark-section section-pad" id="imobiliario"><div className="container"><div className="section-heading"><span className="eyebrow">Imobiliário bancário</span><h2>Não pague pelo atraso da construtora</h2><p>Conheça os direitos que podem proteger o seu patrimônio diante do atraso da obra.</p></div><div className="rights-grid"><article><span>01</span><h3>Fim da Taxa de Obra</h3><p>Suspensão dos juros de obra cobrados após o prazo de entrega.</p></article><article><span>02</span><h3>Multas e Aluguéis</h3><p>Ressarcimento de gastos com moradia e aplicação de multa à construtora.</p></article><article><span>03</span><h3>Danos Morais</h3><p>Compensação pela quebra de expectativa e pelo desgaste causado.</p></article></div><a className="button property-button" href={propertyUrl} target="_blank" rel="noreferrer">Falar com especialista imobiliário <ArrowRight/></a></div></section>

    <section className="about-section-modern section-pad" id="sobre"><div className="container"><div className="about-heading"><div><span className="eyebrow">Quem somos</span><h2>Rigor técnico, proximidade e uma equipe preparada para ouvir você.</h2></div><p>O Mendonça Advogados é liderado pelo Dr. Allyson Mendonça. Layra Mendonça, estudante de Direito, integra a equipe e auxilia no relacionamento e no acolhimento inicial dos clientes.</p></div><div className="team-showcase"><div className="team-photo"><img src={teamPhoto} alt="Dr. Allyson Mendonça e Layra Mendonça, da equipe Mendonça Advogados"/></div><div className="team-copy"><span className="eyebrow">Atendimento próximo</span><h3>Estratégia jurídica com comunicação clara</h3><p>O primeiro contato é uma triagem para entender a situação, organizar as informações e direcionar o atendimento jurídico adequado.</p><div className="team-member"><b>Dr. Allyson Mendonça</b><span>Advogado responsável</span></div><div className="team-member"><b>Layra Mendonça</b><span>Equipe de atendimento · Estudante de Direito</span></div></div></div><div className="headquarters-card"><img src={headquarters} alt="Edifício Norcon Empresarial, sede do Mendonça Advogados"/><div className="headquarters-overlay"><span><Building2/> Nossa sede</span><h3>Edifício Norcon Empresarial</h3><p>Av. Comendador Gustavo Paiva, 2789 · Sala 1004 · Mangabeiras · Maceió/AL</p></div></div><div className="about-bottom"><p>Atendimento presencial em Maceió, mediante agendamento, e atendimento digital em todo o Brasil.</p><div className="location-chip"><MapPin/><span><b>Contato da equipe</b>Layra Mendonça · (82) 9620-0217</span></div></div></div></section>

    <div className="trust-strip"><div className="container"><span><ShieldCheck/> Sigilo e segurança</span><span><Scale/> Análise individual</span><span><MapPin/> Maceió e atendimento digital</span></div></div>
    <section className="final-cta" id="contato"><div className="container"><span className="eyebrow">Atendimento humanizado</span><h2>Conte seu caso para nossa equipe</h2><p>Inicie uma triagem objetiva pelo WhatsApp. O envio das informações não garante a concessão de benefício ou resultado judicial.</p><div className="cta-pair"><a className="button rural-button" href={ruralUrl} target="_blank" rel="noreferrer">Previdenciário Rural</a><a className="button property-button" href={propertyUrl} target="_blank" rel="noreferrer">Imobiliário Bancário</a></div></div></section>
  </>;
}
